site_name: Prof. Flavio Barisi
site_url: https://www.flaviobarisi.it
theme:
  name: material
  language: it

nav:
  - 'index.md'
  - Sistemi 3° anno:
    - 'sistemi-3/index.md'
    - 'sistemi-3/condensatore.md'
    - 'sistemi-3/diodo.md'
  - Sistemi 4° anno:
    - 'sistemi-4/index.md'
    - 'sistemi-4/plc.md'
    - 'sistemi-4/twincat.md'
  - Sistemi 5° anno:
    - 'sistemi-5/index.md'
    - 'sistemi-5/trasduttori.md'
    - 'sistemi-5/attuatori.md'
    - 'sistemi-5/controllo-motore-cc.md'
    - 'sistemi-5/esami-stato.md'
  - Scienze e tecnologie applicate:
    - 'sta/index.md'
    - 'sta/corrente-alternata.md'
    - 'sta/strumentazione.md'

plugins:
    - glightbox
    - search

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/style.css